include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/**.freezed.dart"
    - "**/**.gr.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    prefer_const_constructors: warning
    todo: info
    avoid_classes_with_only_static_members: ignore
    constant_identifier_names: ignore
    file_names: ignore
    avoid_single_cascade_in_expression_statements: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_setters_without_getters: ignore
    non_constant_identifier_names: ignore
    prefer_if_null_operators: ignore
    mixin_application_not_implemented_interface: ignore
    invalid_annotation_target: ignore
    require_trailing_commas: ignore
    depend_on_referenced_packages: ignore

  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    unnecessary_this: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
